import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://student.camu.in/#/');
  await page.getByRole('textbox', { name: 'Type your institution name' }).click();
  await page.getByRole('textbox', { name: 'Type your institution name' }).fill('woxsen');
  await page.getByText('Woxsen University').click();
  await page.locator('input[name="Email"]').click();
  await page.locator('input[name="Email"]').fill('nadirashaik333@gmail.com');
  await page.locator('input[name="pwd"]').click();
  await page.locator('input[name="pwd"]').fill('Irate@8904');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByText('Leave and Gate Pass').click();
  await page.getByRole('button', { name: 'Apply Leave and Gate Pass' }).click();
  await page.locator('.rs-option__control.css-1vlf9f8-control > .rs-option__value-container > .rs-option__input-container').first().click();
  await page.getByRole('option', { name: 'Leave', exact: true }).click();
  await page.getByRole('textbox', { name: 'Start Date' }).click();
  await page.getByRole('cell', { name: '29' }).nth(1).click();
  await page.getByRole('textbox', { name: 'To Date' }).click();
  await page.getByRole('cell', { name: '29' }).nth(1).click();
  await page.getByRole('checkbox').nth(2).check();
  await page.locator('input[name="Frtm"]').click();
  await page.getByText('▲').first().click();
  await page.getByText('▲').first().click();
  await page.getByText('▲').first().click();
  await page.getByText('▲').first().click();
  await page.getByText('▲').first().click();
  await page.getByText('▲').first().click();
  await page.getByText('▲').first().click();
  await page.getByText('▲').first().click();
  await page.getByText('▲').first().click();
  await page.getByText('▲').first().click();
  await page.locator('div').filter({ hasText: 'Leave typeoption Leave,' }).nth(5).click();
  await page.getByRole('option', { name: 'Week End Gate Pass' }).click();
  await page.locator('input[name="ToTm"]').click();
  await page.getByText('▼').nth(3).click();
  await page.getByText('▼').nth(3).click();
  await page.getByText('▼').nth(3).click();
  await page.getByText('▼').nth(3).click();
  await page.locator('div').filter({ hasText: 'Leave typeoption Leave,' }).nth(5).click();
  await page.getByRole('textbox', { name: 'Reason for Absence' }).click();
  await page.getByRole('textbox', { name: 'Reason for Absence' }).fill('outing');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.locator('span').filter({ hasText: 'Timetable' }).first().click();
  await page.getByText('Leave and Gate Pass').click();
  await page.getByRole('button', { name: 'more_horiz', description: 'Options' }).click();
  await page.getByRole('button', { name: 'Status' }).click();
  await page.getByRole('button', { name: 'Approve' }).click();
  await page.getByRole('button', { name: 'Approve' }).nth(1).click();
});